name: Neon
version: 1.1.0
author: jdcraft
api: [3.0.0-ALPHA7]
load: POSTWORLD
main: jdcraft\neon\Main
permissions:
 neon:
  description: all permissions for neon
commands:
 neon:
  description: Neon Commands